# Site settings
theme: jekyll-theme-architect
title: Janine George
email: janine.george[at]rwth-aachen.de 
description: Computational (solid-state) chemistry and physics 
baseurl: "" 
url: "http://jageo.github.io" 
twitter_username: MolecularXtal
